"""empty message

Revision ID: c0020335ada6
Revises: e1e548b2675f
Create Date: 2020-10-12 02:16:50.558716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0020335ada6'
down_revision = 'e1e548b2675f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('dialog_data', sa.LargeBinary(), nullable=True))
    op.drop_column('letters', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('letters', 'dialog_data')
    # ### end Alembic commands ###
